# Generated by Django 3.2.9 on 2022-01-20 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_image'),
        ('project', '0005_auto_20220119_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='user.freelancer'),
        ),
    ]
